%.html: %-b.html uconfig.txt
	/anfs/www/tools/bin/ucampas $*

all:	index.html				\
	20140301-release.html			\
	20140305-release.html			\
	20140313-release.html			\
	20140814-release.html

clean:
	rm -f *~ \#*#
