%.html: %-b.html uconfig.txt
	/anfs/www/tools/bin/ucampas $*

all:	index.html				\
	20130316-release.html			\
	20130320-release.html			\
	20130407-release.html			\
	20130708-release.html			\
	20130722-release.html

clean:
	rm -f *~ \#*#
